"""
Response model returned by the chat endpoint.
"""

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    API response schema.
    """

    intent: str = Field(
        ...,
        description="Detected user intent label"
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score of the classification"
    )

    response: str = Field(
        ...,
        description="Final response generated by the routed expert persona"
    )